# -*- coding: utf-8 -*-
"""App5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKrdCahBIOrnuLpGmpYgjjooF04t9LP5
"""

import streamlit as st

# Title of the app
st.title('Personal Information Form')

# Ask for the user's name
name = st.text_input("What's your name?")

# Display the user's name
if name:
    st.write(f"Hello, {name}!")

    # Ask for the user's age and country once the name is entered
    age = st.number_input("How old are you?", min_value=0, max_value=120, step=1)
    country = st.text_input("Which country are you from?")

    # Display the age and country if entered
    if age >= 0 and country:
        st.write(f"Nice to meet you, {name}!")
        st.write(f"You're {age} years old and you're from {country}.")